<span class="label label-danger">ADMIN</span>
<span class="label label-warning">Warhut Manager</span>
<span class="label label-warning">SR MOD</span>
<span class="label label-warning">MOD</span>
<span class="label label-info">HELPER</span>
<span class="label label-primary">Build Team</span>
<span class="label label-success">YouTuber</span>
<span class="label label-success">Twitch</span>
<span class="label label-warning">✪✪✪</span>
<span class="label label-success">✪✪</span>
<span class="label label-primary">✪</span>
